function DPMSysBioGUI


%% Use system background color for GUI components
panelColor  = get(0,'DefaultUicontrolBackgroundColor');
initial_dir = pwd;

%hs = createGUI;
%set(hs.fig, 'Visible', 'on')

% % load_listbox(initial_dir)
%% ------------ Callback Functions ---------------

% Figure resize function
    function figResize(src,evt)
        fpos = get(f,'Position');
        set(botPanel,'Position',...
            [1/20 1/20 fpos(3)-.1 fpos(4)*8/35])
        set(rightPanel,'Position',...
            [fpos(3)*85/120 fpos(4)*8/35 fpos(3)*35/120 fpos(4)*27/35])
        set(centerPanel,'Position',...
            [1/20 fpos(4)*8/35 fpos(3)*85/120 fpos(4)*27/35]);
    end

% Bottom panel resize function
    function botPanelResize(src, evt)
        bpos = get(botPanel,'Position');
        set(plotButton,'Position',...
            [bpos(3)*10/120 bpos(4)*2/8 bpos(3)*24/120 2])
    end

% Right panel resize function
    function rightPanelResize(src,evt)
        rpos = get(rightPanel,'Position');
        set(listBox,'Position',...
            [rpos(3)*3.5/32 rpos(4)*1/27 rpos(3)*25/32 rpos(4)*10/27]);
        set(popUpLabel,'Position',...
            [rpos(3)*.6/32 rpos(4)*12.5/27 rpos(3)*20/32 rpos(4)*3/27]);
        set(listBoxLabel,'Position',...
            [rpos(3)*3/32 rpos(4)*10.2/27 rpos(3)*12/32 rpos(4)*2/27]);
        %
    end

    function load_listbox(dir_path)
        cd (dir_path)
        dir_struct = dir(dir_path);
        dir_struct = dir_struct([dir_struct.isdir]);
        dir_struct2 = dir('*.csv');
        sorted_names1 = sortrows({dir_struct.name}');
        sorted_names2 = sortrows({dir_struct2.name}');
        sorted_names = [sorted_names1; sorted_names2];
        %        handles.is_dir = [dir_struct.isdir];
        %        handles.sorted_index = sorted_index;
        % guidata(handles.figure1,handles)
        set(listBox,'String',sorted_names,...
            'Value',1)
        %set(handles.text1,'String',pwd)
        
    end




%function listbox1_Callback(hObject, eventdata, handles)
% hObject    handle to listbox1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: contents = get(hObject,'String') returns listbox1 contents as cell array
%        contents{get(hObject,'Value')} returns selected item from listbox1


%% Callback for list box
    function listBoxCallback(src,evt, handles)
        % Load workspace vars into list box
        %vars = evalin('base','who');
        %set(src,'String',vars)
        index_selected = get(listBox,'Value');
        file_list = get(listBox,'String');
        filename = file_list{index_selected};
        if  isdir(filename)
            cd (filename)
            load_listbox(pwd)
            %         else
            %             set(src,'String',vars)
        end
        
    end % listBoxCallback

%% Callback for plot button
    function plotButtonCallback(src,evt)
        selectedButton = get(buttongroup, 'SelectedObject');
        selectedButtonTag = get(selectedButton, 'Tag');
        
        switch selectedButtonTag
            case 'timeCourseEqual'   %%% DEPRECATED CASE
                fHandle = @DPCluster_TimeCourseEqual;
                dataType = 'TimeCourseEqualSpacing';
            case 'timeCourseUnequal'
                fHandle = @DPCluster_TimeCourseUnequal;
                dataType = 'TimeCourseUnequalSpacing';
                
            case 'multinomial'
                fHandle = @DPCluster_Multinomial;
                dataType = 'Multinomial';
                
            case 'bagOfWords'
                fHandle = @DPCluster_BagOfWords;
                dataType = 'BagOfWords';
                
        end
        
        nSamplesLabel = get(dropDown, 'Value');
        
        switch nSamplesLabel
            case 1
                nSamples = 1;
            case 2
                nSamples = 10;
            case 3
                nSamples = 100;
            case 4
                nSamples = 500;
            case 5
                nSamples = 1000;
            case 6
                nSamples = 2000;
            case 7
                nSamples = 5000;
            case 8
                nSamples = 10000;
            case 9
                nSamples = 20000;
            case 10
                nSamples = 50000;
            case 11
                nSamples = 100000;
                
        end
        
        
        index_selected = get(listBox,'Value');
        file_list = get(listBox,'String');
        fileName = file_list{index_selected};
        
        
        uniqueIdentifier = 1;
        drawFigures      = true;
        
        hyperParameterSamplingFrequency = 1;
        verbose       = false;
        initialise    = true;
        gammaPrior    = [2 4];
        thinningFreq  = 1;
        inputSeed     = nan;
        
        
        feval(fHandle, fileName, uniqueIdentifier, nSamples, dataType, ...
            drawFigures, hyperParameterSamplingFrequency, verbose, initialise, ...
            gammaPrior, thinningFreq,inputSeed,true,centerPanel);
        
        
        
        
    end

%% ------------ GUI layout ---------------

%    function handles = createGUI
%% Set up the figure and defaults
f = figure('Tag','fig',...
    'Units','characters',...
    'Position',[30 30 120 35],...
    'Color',panelColor,...
    'HandleVisibility','callback',...
    'IntegerHandle','off',...
    'Renderer','painters',...
    'Toolbar','figure',...
    'NumberTitle','off',...
    'Name','DPM SysBio',...
    'ResizeFcn',@figResize, ...
    'Visible', 'off');

handles = guihandles(f);

%% Create the bottom uipanel
botPanel = uipanel('BorderType','etchedin',...
    'BackgroundColor',panelColor,...
    'Units','characters',...
    'Position',[1/20 1/20 119.9 8],...
    'Parent',f,...
    'ResizeFcn',@botPanelResize);

%% Create the right side panel
rightPanel = uipanel('bordertype','etchedin',...
    'BackgroundColor',panelColor,...
    'Units','characters',...
    'Position',[88 8 32 27],...
    'Parent',f,...
    'ResizeFcn',@rightPanelResize);

%% Create the center panel
centerPanel = uipanel('bordertype','etchedin',...
    'Units','characters',...
    'Position', [1/20 8 88 27],...
    'Parent',f, 'Title', 'Select data type, number of samples and file, then hit "Start sampler"');

%% Add an axes to the center panel
%a = axes('parent',centerPanel);

%% Add listbox and label
% buttonGroupLabel = uicontrol(f,'Style','text','Units','characters',...
%     'Position',[2 12 12 1],...
%     'String','Select data type',...
%     'BackgroundColor',panelColor,...
%     'Parent',rightPanel);

listBoxLabel = uicontrol(f,'Style','text','Units','characters',...
    'Position',[3 10.4 10 2],...
    'String','Select data file:',...
    'BackgroundColor',panelColor,...
    'Parent',rightPanel);


listBox = uicontrol(f,'Style','listbox','Units','characters',...
    'Position',[3.5 1 28 10],...
    'BackgroundColor','white',...
    'Max',5,'Min',1,...
    'Parent',rightPanel,...
    'Callback',@listBoxCallback);

load_listbox(initial_dir)

plotButton = uicontrol(f,'Style','pushbutton','Units','characters',...
    'Position',[10 2 24 2],...
    'String','Start sampler',...
    'Parent',botPanel,...
    'Callback',@plotButtonCallback);



buttongroup = uibuttongroup(...
    'Parent',rightPanel,...
    'FontUnits','pixels',...
    'FontSize',10.0064045278522,...
    'Title',{  'Data type' },...
    'Tag','uipanel1',...
    'Clipping','on',...
    'Position',[0.0970873786407767 0.609933774834437 0.820388349514563 0.390728476821192],...
    'SelectedObject',[],...
    'SelectionChangeFcn',[],...
    'OldSelectedObject',[]);%,...


h11 = uicontrol(...
    'Parent',buttongroup,...
    'Units','normalized',...
    'FontUnits','pixels',...
    'FontSize',10.0064045278522,...
    'Position',[0.103030303030303 0.754004329004329 0.56969696969697 0.261363636363636],...
    'String','Discrete',...
    'Style','radiobutton',...
    'Value',1,...
    'Tag','multinomial');%,...

appdata = [];
appdata.lastValidTag = 'radiobutton2';

h12 = uicontrol(...
    'Parent',buttongroup,...
    'Units','normalized',...
    'FontUnits','pixels',...
    'FontSize',10.0064045278522,...
    'Position',[0.103030303030303 0.323809523809524 0.854545454545454 0.257142857142857],...
    'String','Time course',...
    'Style','radiobutton',...
    'Tag','timeCourseUnequal');%,...

%    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'radiobutton3';

h13 = uicontrol(...
    'Parent',buttongroup,...
    'Units','normalized',...
    'FontUnits','pixels',...
    'FontSize',10.0064045278522,...
    'Position',[0.103030303030303 0.542857142857143 0.56969696969697 0.257142857142857],...
    'String','Binary',...
    'Style','radiobutton',...
    'Tag','bagOfWords');%,...

appdata = [];
appdata.lastValidTag = 'radiobutton4';


appdata = [];
appdata.lastValidTag = 'popupmenu2';

popUpLabel = uicontrol(f,'Style','text','Units','characters',...
    'Position',[3 12.5 10 3],...
    'String','Number of samples:',...
    'BackgroundColor',panelColor,...
    'Parent',rightPanel);



dropDown = uicontrol(...
    'Parent',rightPanel,...
    'Units','normalized',...
    'FontUnits','pixels',...
    'FontSize',10.0064045278522,...
    'Position',[0.0970873786407767 0.189933774834437 0.820388349514563 0.350728476821192],...
    'String',{  '1'; '10'; '100'; '500'; '1000'; '2000'; '5000'; '10000'; '20000'; '50000'; '100000' },...
    'Style','popupmenu',...
    'Value',1,...
    'Tag','popupmenu2');%,...

appdata = [];
appdata.lastValidTag = blanks(0);
%    end
set(handles.fig, 'Visible','on');

end